<?php
// ============================================================
// SETUP ONE-SHOT DE CREDENCIAIS — APAGAR APÓS USO
// ------------------------------------------------------------
// Acesso:
//   https://vilela.eng.br/contato/area-cliente/setup_credentials.php
//     ?token=c1022059402d6329bc54f5411ca21629
//
// Função: gravar /core/db_credentials.php no servidor a partir
// de um formulário web — bypassa o problema atual de credenciais
// geradas em CI não chegarem via FTP.
//
// IMPORTANTE: usar uma vez, clicar "Excluir esta página" depois.
// ============================================================

session_start();

const SETUP_TOKEN = 'c1022059402d6329bc54f5411ca21629';
const TARGET = __DIR__ . '/core/db_credentials.php';

// 1) Sem token = 404 silencioso (não revela existência do arquivo)
if (!hash_equals(SETUP_TOKEN, $_GET['token'] ?? '')) {
    http_response_code(404);
    echo '<!doctype html><title>404</title><h1>404 Not Found</h1>';
    exit;
}

// 2) Action: self-destruct
if (($_GET['action'] ?? '') === 'self_destruct') {
    $deleted = @unlink(__FILE__);
    if ($deleted) {
        header('Location: /contato/area-cliente/');
        exit;
    }
    // Se unlink falhar, segue pro fluxo normal mostrando aviso
}

// 3) POST: salvar credenciais
$saved = false;
$error = null;
$values = [
    'DB_HOST' => 'srv1074.hstgr.io',
    'DB_NAME' => 'u884436813_cliente',
    'DB_USER' => '',
    'DB_PASS' => '',
    'ADMIN_PASSWORD' => '',
];

// Pre-fill via query params (não persistido — só pra conveniência ao clicar link gerado)
foreach (array_keys($values) as $k) {
    if (isset($_GET[$k]) && is_string($_GET[$k]) && $_GET[$k] !== '') {
        $values[$k] = $_GET[$k];
    }
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!hash_equals($_SESSION['csrf'] ?? '!', $_POST['csrf'] ?? '')) {
        $error = 'Token CSRF inválido. Recarregue a página e tente de novo.';
    } else {
        $fields = ['DB_HOST', 'DB_NAME', 'DB_USER', 'DB_PASS', 'ADMIN_PASSWORD'];
        $data = [];
        foreach ($fields as $f) {
            $v = trim((string)($_POST[$f] ?? ''));
            $values[$f] = $v;
            if ($v === '') {
                $error = "Campo $f é obrigatório.";
                break;
            }
            $data[$f] = $v;
        }

        if (!$error) {
            // Garante que /core/ existe
            $core_dir = dirname(TARGET);
            if (!is_dir($core_dir)) {
                $error = "Diretório $core_dir não existe no servidor.";
            } else {
                $hdr = "<?php\n// Generated by setup_credentials.php at " . gmdate('c') . "\n// DO NOT COMMIT. Generated automatically.\nreturn ";
                $payload = $hdr . var_export($data, true) . ";\n";
                $ok = @file_put_contents(TARGET, $payload);
                if ($ok === false) {
                    $error = 'Falha ao escrever ' . TARGET . '. Verifique permissões do diretório /core/.';
                } else {
                    @chmod(TARGET, 0640);
                    $saved = true;
                }
            }
        }
    }
}

// 4) CSRF token (renovado a cada GET)
if ($_SERVER['REQUEST_METHOD'] !== 'POST' || $error) {
    $_SESSION['csrf'] = bin2hex(random_bytes(16));
}
$csrf = $_SESSION['csrf'];

$self_destruct_url = '?token=' . urlencode(SETUP_TOKEN) . '&action=self_destruct';
$target_exists = file_exists(TARGET);
?><!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Setup de Credenciais — Vilela Engenharia</title>
<style>
  :root {
    --green: #197e63;
    --green-strong: #146c43;
    --bg: #f8f9fa;
    --surface: #fff;
    --text: #1a1a1a;
    --subtle: #4a5568;
    --danger: #b42318;
    --success: #067647;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0;
    font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
    background: var(--bg);
    color: var(--text);
    line-height: 1.5;
    padding: 24px 16px 60px;
    min-height: 100vh;
  }
  .wrap { max-width: 560px; margin: 0 auto; }
  h1 { font-size: 1.4rem; margin: 0 0 4px; color: var(--green); }
  .lead { color: var(--subtle); font-size: 0.95rem; margin: 0 0 24px; }
  .card {
    background: var(--surface);
    border-radius: 12px;
    padding: 24px;
    box-shadow: 0 8px 24px rgba(0,0,0,0.06);
    margin-bottom: 16px;
  }
  label { display: block; font-weight: 600; font-size: 0.85rem; margin-bottom: 4px; color: var(--text); }
  .hint { display: block; font-size: 0.78rem; color: var(--subtle); margin-top: 2px; font-weight: 400; }
  input[type=text], input[type=password] {
    width: 100%; padding: 10px 12px; border: 1.5px solid #d0d5dd;
    border-radius: 8px; font-size: 0.95rem; font-family: inherit;
    background: #fafbfc; margin-bottom: 14px;
  }
  input:focus { outline: 2px solid var(--green); border-color: var(--green); background: #fff; }
  button, .btn {
    display: inline-block; padding: 12px 20px; border-radius: 999px;
    font-weight: 700; font-size: 0.95rem; cursor: pointer; border: none;
    text-decoration: none; font-family: inherit;
  }
  .btn-primary { background: var(--green); color: white; }
  .btn-primary:hover { background: var(--green-strong); }
  .btn-danger { background: var(--danger); color: white; }
  .btn-danger:hover { filter: brightness(0.9); }
  .btn-ghost { background: transparent; color: var(--subtle); border: 1px solid #d0d5dd; }
  .alert { padding: 12px 14px; border-radius: 8px; font-size: 0.9rem; margin-bottom: 16px; }
  .alert-error { background: #fef3f2; color: var(--danger); border: 1px solid #fda29b; }
  .alert-success { background: #ecfdf3; color: var(--success); border: 1px solid #abefc6; }
  .alert-info { background: #eff8ff; color: #175cd3; border: 1px solid #b2ddff; }
  code { background: #f1f3f5; padding: 1px 6px; border-radius: 4px; font-size: 0.85em; }
  .row-actions { display: flex; gap: 12px; flex-wrap: wrap; margin-top: 8px; }
</style>
</head>
<body>
<div class="wrap">
  <h1>Setup de Credenciais</h1>
  <p class="lead">Página one-shot para gravar <code>core/db_credentials.php</code> no servidor. <strong>Exclua após uso.</strong></p>

  <?php if ($error): ?>
    <div class="alert alert-error">❌ <?= htmlspecialchars($error) ?></div>
  <?php endif; ?>

  <?php if ($saved): ?>
    <div class="card">
      <div class="alert alert-success">✅ Credenciais salvas em <code>core/db_credentials.php</code>.</div>
      <p>Agora você pode:</p>
      <div class="row-actions">
        <a class="btn btn-primary" href="/contato/area-cliente/">Ir para a área cliente</a>
        <a class="btn btn-danger" href="<?= htmlspecialchars($self_destruct_url) ?>" onclick="return confirm('Excluir esta página de setup? Não dá pra desfazer — você precisaria de novo push pra recriar.')">🗑 Excluir esta página agora</a>
      </div>
      <p style="margin-top: 20px; font-size: 0.85rem; color: var(--subtle);">
        <strong>Dica:</strong> sempre excluir antes de deixar a página por aí. Se o botão falhar (permissão), apague manualmente via FTP/File Manager.
      </p>
    </div>
  <?php else: ?>
    <?php if ($target_exists): ?>
      <div class="alert alert-info">⚠️ <code>core/db_credentials.php</code> <strong>já existe</strong> no servidor. Salvar abaixo vai sobrescrever.</div>
    <?php endif; ?>
    <form method="POST" class="card" autocomplete="off">
      <input type="hidden" name="csrf" value="<?= htmlspecialchars($csrf) ?>">

      <label>DB_HOST <span class="hint">Servidor MySQL da Hostinger</span></label>
      <input type="text" name="DB_HOST" value="<?= htmlspecialchars($values['DB_HOST']) ?>" placeholder="srv1074.hstgr.io" required>

      <label>DB_NAME <span class="hint">Nome do banco</span></label>
      <input type="text" name="DB_NAME" value="<?= htmlspecialchars($values['DB_NAME']) ?>" placeholder="u884436813_cliente" required>

      <label>DB_USER <span class="hint">Usuário do banco</span></label>
      <input type="text" name="DB_USER" value="<?= htmlspecialchars($values['DB_USER']) ?>" placeholder="u884436813_xxxxx" required>

      <label>DB_PASS <span class="hint">Senha do banco MySQL</span></label>
      <input type="password" name="DB_PASS" value="<?= htmlspecialchars($values['DB_PASS']) ?>" required>

      <label>ADMIN_PASSWORD <span class="hint">Senha do admin pra entrar em <code>admin.php</code></span></label>
      <input type="password" name="ADMIN_PASSWORD" value="<?= htmlspecialchars($values['ADMIN_PASSWORD']) ?>" required>

      <div class="row-actions">
        <button type="submit" class="btn btn-primary">💾 Salvar credenciais</button>
        <a class="btn btn-ghost" href="<?= htmlspecialchars($self_destruct_url) ?>" onclick="return confirm('Excluir esta página sem salvar?')">Cancelar e excluir</a>
      </div>
    </form>
  <?php endif; ?>

  <p style="font-size: 0.8rem; color: var(--subtle); text-align: center; margin-top: 32px;">
    Esta página existe APENAS porque os arquivos gerados em CI não chegaram via FTP.<br>
    Depois de salvar, exclua imediatamente.
  </p>
</div>
</body>
</html>
